###  Python and NumPy

Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions.

NumPy and python work together fairly seamlessly.

In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

### Vectors

NumPy Arrays

A NumPy array is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Vectors are one-dimensional NumPy arrays.

Vector Creation

In [6]:
# Create a vector (1D array)
vector = np.array([1, 2, 3])
b = np.zeros(3)
c = np.ones(3)
d = np.random.rand(3)
print("Vector:", vector)
print("Zeros:", b)
print("Ones:", c)
print("Random:", d)

Vector: [1 2 3]
Zeros: [0. 0. 0.]
Ones: [1. 1. 1.]
Random: [0.94621834 0.88550478 0.52980093]


### Operations on Vectors (Indexing and Slicing)

Indexing: Accessing elements in a vector using their position.

Slicing: Extracting a portion of the vector.

In [7]:
# Access elements
print("First element:", vector[0])

# Slice the vector
print("Elements from index 1 to end:", vector[1:])

First element: 1
Elements from index 1 to end: [2 3]


### Vector-Vector Element-wise Operations

Operations performed element-wise on vectors of the same size.

In [9]:
# Create another vector
vector2 = np.array([4, 5, 6])

print("vector:", vector)
print("vector2:", vector2)

# Element-wise addition
print("Element-wise Addition:", vector + vector2)

# Element-wise multiplication
print("Element-wise Multiplication:", vector * vector2)

vector: [1 2 3]
vector2: [4 5 6]
Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


### Scalar-Vector Operations
Operations between a vector and a scalar (a single number) are broadcast across all elements of the vector.

In [10]:
# Scalar multiplication
scalar = 2
print("Scalar:", scalar)
print("vector:", vector)
print("Scalar Multiplication:", scalar * vector)

Scalar: 2
vector: [1 2 3]
Scalar Multiplication: [2 4 6]


### Vector Dot Product
The dot product of two vectors is a single number obtained by multiplying corresponding elements and summing the results.

In [11]:
# Dot product
dot_product = np.dot(vector, vector2)
print("vector:", vector)
print("vector2:", vector2)
print("Dot Product:", dot_product)

vector: [1 2 3]
vector2: [4 5 6]
Dot Product: 32


### Need for Speed: Vector vs. For Loop
NumPy operations are highly optimized and typically faster than using a Python for-loop for element-wise operations.

In [12]:
# Using a loop to calculate element-wise addition
result = np.zeros(len(vector))
for i in range(len(vector)):
    result[i] = vector[i] + vector2[i]

print("Result using loop:", result)

# Using NumPy for the same operation
print("Result using NumPy:", vector + vector2)

Result using loop: [5. 7. 9.]
Result using NumPy: [5 7 9]


In [16]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0.0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [17]:
my_dot(vector, vector2)

32.0

In [18]:
np.random.seed(1)
m = np.random.rand(10000000)  # very large arrays
n = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(m, n)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(m, n)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(m);del(n)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 16.2127 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 7649.6985 ms 


### Matrices
NumPy Arrays
Matrices are 2D arrays in NumPy, which means they have rows and columns.

### Matrix Creation

In [19]:
# Create a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


### Operations on Matrices
Indexing and Slicing: Similar to vectors, but with two indices.

In a 2D array, inner each array represents a single record like 
Matrix:[[1 2 3][4 5 6]]
suupose Matrix is a customer table where you can find multiple customers having name, contact, address, so
[1 2 3] this belongs to Customer1, [4 5 6] belongs to Customer 2

In [21]:
# Access an element
print("Element at row 0, column 1:", matrix[0, 1])

# Slice a submatrix
print("First row:", matrix[0, :])

Element at row 0, column 1: 2
First row: [1 2 3]


Element-wise Operations: Performed element-wise between matrices of the same shape.

In [23]:
# Create another matrix
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix:\n", matrix)
print("Matrix2:\n", matrix2)

# Element-wise addition
print("Element-wise Addition:\n", matrix + matrix2)

Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]


Scalar-Matrix Operations: Scalars are broadcasted across the matrix.

In [24]:
# Scalar multiplication
print("Matrix:\n", matrix)
print("Scalar Multiplication:\n", 2 * matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]
Scalar Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]


Matrix-Matrix Multiplication: Dot product for matrices is performed using np.dot() or @.

In [26]:
# Matrix multiplication
matrix3 = np.array([[1, 2], [3, 4], [5, 6]])
product = np.dot(matrix, matrix3)  # or matrix @ matrix3
print("Matrix:\n", matrix)
print("Matrix3:\n", matrix3)
print("Matrix Multiplication:\n", product)

Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix3:
 [[1 2]
 [3 4]
 [5 6]]
Matrix Multiplication:
 [[22 28]
 [49 64]]
